// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

// ...
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqYISQH2h2D4XGyn8rENKZxMnvduzerOg',
    appId: '1:496808365028:web:6841d3ab742f0615a855f1',
    messagingSenderId: '496808365028',
    projectId: 'assemble-a1341',
    authDomain: 'assemble-a1341.firebaseapp.com',
    storageBucket: 'assemble-a1341.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-vfFos6wMmPvtlTXQTRr3udwO9eE6V8',
    appId: '1:496808365028:android:3d5cb3bbb3e2054ba855f1',
    messagingSenderId: '496808365028',
    projectId: 'assemble-a1341',
    storageBucket: 'assemble-a1341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZEgeTNKRCxv_vsHcs4xjwx8SWpUHkCXI',
    appId: '1:496808365028:ios:1886e01fc2d974d1a855f1',
    messagingSenderId: '496808365028',
    projectId: 'assemble-a1341',
    storageBucket: 'assemble-a1341.firebasestorage.app',
    iosBundleId: 'com.example.assemble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZEgeTNKRCxv_vsHcs4xjwx8SWpUHkCXI',
    appId: '1:496808365028:ios:1886e01fc2d974d1a855f1',
    messagingSenderId: '496808365028',
    projectId: 'assemble-a1341',
    storageBucket: 'assemble-a1341.firebasestorage.app',
    iosBundleId: 'com.example.assemble',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqYISQH2h2D4XGyn8rENKZxMnvduzerOg',
    appId: '1:496808365028:web:ca0f6f502d4ad133a855f1',
    messagingSenderId: '496808365028',
    projectId: 'assemble-a1341',
    authDomain: 'assemble-a1341.firebaseapp.com',
    storageBucket: 'assemble-a1341.firebasestorage.app',
  );
}
